version: '3.1'

services:
  web:
    container_name: apache
    image: apache_press_plus
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/html"

  db:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: haslohaslo123
    ports:
      - "3306:3306"
    volumes:
      - db-vol:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"

volumes:
  db-vol:
  db:
    driver: local